### PR TITLE
Sourceline pc eval

### PR DESCRIPTION
**Pull request by jeho-oh**
merged static method fix from Paul and changed superc sommand to run on turing

### CODE REVIEW

**Comment by paulgazz** [comment]
This is pretty hacky, but if it’s needed, then I don’t object.  @necipfazil is this acceptable for now?

**Comment by necipfazil** [comment]
I did not test this but the changes LGTM. @jeho-oh could you verify that we get a reasonable output for demo patch (especially the superc output generated within plocalizer, i.e., the sourceline pcs file for the file modified by the patch)?

**Comment by jeho-oh** [comment]
It worked well with the patch in the /assets folder, and for the other Linux patches I tried, at least it did not cause the issue at hand.  It seems this fix is fine.

**Comment by jeho-oh** [comment]
I will close this request as I need to revert the changes I made.  I'll make a new pull request.

**Pull request closed without merging**
